services:
  fastapi-interpretepy_service:
    build:
      context: .
    ports:
      - "8003:8000"
    volumes:
      - .:/code  
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password  
      MYSQL_DATABASE: interpretePy
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql 

volumes:
  mysql-data:
