services:
  fastapi-interpretepy_service:
    build:
      context: .
    ports:
      - "8003:8000"
    volumes:
      - .:/code
    # Ya no es necesario el "depends_on" con mysql
    # depends_on:
    #   - mysql
